- name: install node nodejs serice
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed      
    
- name: add application user    
  ansible.builtin.user:
    name: roboshop
    
- name: Download and UnZip the catalogue Content
  ansible.builtin.import_role:
    name: common
    tasks_from: download 
    
- name: Remove old app content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy the new app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
  become_user: roboshop
  
- name: Install NodejS Dependencies.
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop
